export const SITE = {
  name: "ZenLab",
  legalName: "ZenLab Inc.",
  nameJa: "株式会社ゼンラボ",
  url: "https://zenlab.co.jp",
  domain: "zenlab.co.jp",
  tagline: "業務に溶け込む、自律するAIを。",
  taglineEn: "Quiet AI for real work.",
  description:
    "ZenLab(株式会社ゼンラボ)は、AI組織をうまく運営していることを売りにするAIエンジニアリングスタジオです。AI組織運営コンサルとシステム開発受託を通じて、顧客の業務成果にコミットします。",
  email: "hello@zenlab.co.jp",
  phone: "050-8888-5921",
  contactPath: "/#contact",
  founded: "2026年5月",
  representative: "畑田 祐陽",
  representativeKana: "はただ ゆうひ",
  representativeRomaji: "Yuhi Hatada",
  businessDescription: "人工知能(AI)・機械学習・ロボティクスを活用したソフトウェア、システム及びサービスの企画、開発、運用、保守及び販売",
  addressZip: "160-0022",
  addressLine1: "東京都新宿区新宿2丁目8番15号",
  addressLine2: "パークフロント新宿 202号室",
} as const;
