export const SITE = {
  name: "ZenLab",
  legalName: "ZenLab Inc.",
  nameJa: "株式会社ZenLab",
  url: "https://zenlab.co.jp",
  domain: "zenlab.co.jp",
  tagline: "AI / ロボットが自律して、社会インフラを運営する世界をつくる。",
  taglineEn: "AI teams that run the business.",
  description:
    "ZenLab(株式会社ZenLab)は、個人の創造を手助けする道具づくりに取り組んでいます。AI・ソフトウェア・ロボティクスを使った試作・開発と、企業向けの業務のAI化支援を行っています。",
  email: "info@zenlab.co.jp",
  contactPath: "/#contact",
  founded: "2026年5月",
  representative: "畑田 祐陽",
  representativeKana: "はただ ゆうひ",
  representativeRomaji: "Yuhi Hatada",
  businessDescription: "人工知能(AI)・機械学習・ロボティクスを活用したソフトウェア、システム及びサービスの企画、開発、運用、保守及び販売",
  addressZip: "160-0022",
  addressLine1: "東京都新宿区新宿2丁目8番15号",
  addressLine2: "パークフロント新宿 202号室",
} as const;
